"""Initial

Revision ID: 1a2b15a3ecfc
Revises: 
Create Date: 2015-03-04 04:14:25.021249

"""

# revision identifiers, used by Alembic.
revision = '1a2b15a3ecfc'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_fact',
    sa.Column('provider_id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('nval_num', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('confidence_num', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('encounter_num', sa.Numeric(precision=38, scale=0), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('valueflag_cd', sa.String(length=50), nullable=True),
    sa.Column('tval_char', sa.String(length=255), nullable=True),
    sa.Column('modifier_cd', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('patient_num', sa.Numeric(precision=38, scale=0), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instance_num', sa.Numeric(precision=18, scale=0), server_default='1', autoincrement=False, nullable=False),
    sa.Column('sourcesystem_cd', sa.String(length=50), nullable=True),
    sa.Column('concept_cd', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('observation_blob', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('quantity_num', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('valtype_cd', sa.String(length=50), nullable=True),
    sa.Column('units_cd', sa.String(length=50), nullable=True),
    sa.Column('location_cd', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('patient_num', 'concept_cd', 'modifier_cd', 'start_date', 'encounter_num', 'instance_num', 'provider_id', name=op.f('pk_observation_fact'))
    )
    op.create_index(op.f('ix_observation_fact_concept_cd'), 'observation_fact', ['concept_cd'], unique=False, postgresql_ops={u'concept_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_observation_fact_concept_cd_instance_num_patient_num_encounter_num'), 'observation_fact', ['concept_cd', 'instance_num', 'patient_num', 'encounter_num'], unique=False, postgresql_ops={u'concept_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_observation_fact_encounter_num'), 'observation_fact', ['encounter_num'], unique=False, postgresql_ops={})
    op.create_index(op.f('ix_observation_fact_patient_num_concept_cd_modifier_cd_start_date_encounter_num_instance_num_provider_id'), 'observation_fact', ['patient_num', 'concept_cd', 'modifier_cd', 'start_date', 'encounter_num', 'instance_num', 'provider_id'], unique=False, postgresql_ops={u'concept_cd': u'varchar_pattern_ops', u'provider_id': u'varchar_pattern_ops', u'modifier_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_observation_fact_patient_num_concept_cd_start_date_end_date_encounter_num_instance_num_provider_id_nval_num_valtype_cd'), 'observation_fact', ['patient_num', 'concept_cd', 'start_date', 'end_date', 'encounter_num', 'instance_num', 'provider_id', 'nval_num', 'valtype_cd'], unique=False, postgresql_ops={u'concept_cd': u'varchar_pattern_ops', u'provider_id': u'varchar_pattern_ops', u'valtype_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_observation_fact_patient_num_start_date_concept_cd_encounter_num_instance_num_nval_num_tval_char_valtype_cd_modifier_cd_valueflag_cd_provider_id_quantity_num_units_cd_end_date_location_cd_confidence_num_update_date_download_date_import_date_sourcesystem_cd_upload_id'), 'observation_fact', ['patient_num', 'start_date', 'concept_cd', 'encounter_num', 'instance_num', 'nval_num', 'tval_char', 'valtype_cd', 'modifier_cd', 'valueflag_cd', 'provider_id', 'quantity_num', 'units_cd', 'end_date', 'location_cd', 'confidence_num', 'update_date', 'download_date', 'import_date', 'sourcesystem_cd', 'upload_id'], unique=False, postgresql_ops={u'concept_cd': u'varchar_pattern_ops', u'provider_id': u'varchar_pattern_ops', u'valueflag_cd': u'varchar_pattern_ops', u'sourcesystem_cd': u'varchar_pattern_ops', u'tval_char': u'varchar_pattern_ops', u'modifier_cd': u'varchar_pattern_ops', u'units_cd': u'varchar_pattern_ops', u'location_cd': u'varchar_pattern_ops', u'valtype_cd': u'varchar_pattern_ops'})
    op.create_table('concept_dimension',
    sa.Column('concept_cd', sa.String(length=50), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('concept_blob', sa.Text(), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('name_char', sa.String(length=2000), nullable=True),
    sa.Column('concept_path', sa.String(length=700), autoincrement=False, nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('upload_id', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('sourcesystem_cd', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('concept_path', name=op.f('pk_concept_dimension'))
    )
    op.create_index(op.f('ix_concept_dimension_concept_path'), 'concept_dimension', ['concept_path'], unique=False, postgresql_ops={u'concept_path': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_concept_dimension_upload_id'), 'concept_dimension', ['upload_id'], unique=False, postgresql_ops={})
    op.create_table('patient_dimension',
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('zip_cd', sa.String(length=50), nullable=True),
    sa.Column('race_cd', sa.String(length=50), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('marital_status_cd', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('patient_blob', sa.Text(), nullable=True),
    sa.Column('vital_status_cd', sa.String(length=50), nullable=True),
    sa.Column('income_cd', sa.String(length=50), nullable=True),
    sa.Column('religion_cd', sa.String(length=50), nullable=True),
    sa.Column('sex_cd', sa.String(length=50), nullable=True),
    sa.Column('patient_num', sa.Numeric(precision=38, scale=0), autoincrement=False, nullable=False),
    sa.Column('age_in_years_num', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('upload_id', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('statecityzip_path', sa.String(length=50), nullable=True),
    sa.Column('language_cd', sa.String(length=50), nullable=True),
    sa.Column('ethnicity_cd', sa.String(length=50), nullable=True),
    sa.Column('sourcesystem_cd', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('patient_num', name=op.f('pk_patient_dimension'))
    )
    op.create_index(op.f('ix_patient_dimension_patient_num'), 'patient_dimension', ['patient_num'], unique=False, postgresql_ops={})
    op.create_index(op.f('ix_patient_dimension_patient_num_vital_status_cd_birth_date_death_date'), 'patient_dimension', ['patient_num', 'vital_status_cd', 'birth_date', 'death_date'], unique=False, postgresql_ops={u'vital_status_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_patient_dimension_patient_num_vital_status_cd_birth_date_death_date_sex_cd_age_in_years_num_language_cd_race_cd_marital_status_cd_religion_cd_zip_cd_income_cd'), 'patient_dimension', ['patient_num', 'vital_status_cd', 'birth_date', 'death_date', 'sex_cd', 'age_in_years_num', 'language_cd', 'race_cd', 'marital_status_cd', 'religion_cd', 'zip_cd', 'income_cd'], unique=False, postgresql_ops={u'zip_cd': u'varchar_pattern_ops', u'race_cd': u'varchar_pattern_ops', u'marital_status_cd': u'varchar_pattern_ops', u'vital_status_cd': u'varchar_pattern_ops', u'religion_cd': u'varchar_pattern_ops', u'sex_cd': u'varchar_pattern_ops', u'income_cd': u'varchar_pattern_ops', u'language_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_patient_dimension_statecityzip_path_patient_num'), 'patient_dimension', ['statecityzip_path', 'patient_num'], unique=False, postgresql_ops={u'statecityzip_path': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_patient_dimension_upload_id'), 'patient_dimension', ['upload_id'], unique=False, postgresql_ops={})
    op.create_table('i2b2',
    sa.Column('c_columndatatype', sa.String(length=50), nullable=False),
    sa.Column('c_dimcode', sa.String(length=700), nullable=False),
    sa.Column('c_name', sa.String(length=2000), nullable=False),
    sa.Column('c_facttablecolumn', sa.String(length=50), nullable=False),
    sa.Column('c_basecode', sa.String(length=50), nullable=True),
    sa.Column('c_fullname', sa.String(length=700), nullable=False),
    sa.Column('c_tablename', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('m_exclusion_cd', sa.String(length=25), nullable=True),
    sa.Column('c_synonym_cd', sa.String(length=1), nullable=False),
    sa.Column('valuetype_cd', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('c_visualattributes', sa.String(length=3), nullable=False),
    sa.Column('c_symbol', sa.String(length=50), nullable=True),
    sa.Column('m_applied_path', sa.String(length=700), nullable=False),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('c_operator', sa.String(length=10), nullable=False),
    sa.Column('sourcesystem_cd', sa.String(length=50), nullable=True),
    sa.Column('c_hlevel', sa.Numeric(precision=22, scale=0), nullable=False),
    sa.Column('c_columnname', sa.String(length=50), nullable=False),
    sa.Column('c_totalnum', sa.Numeric(precision=22, scale=0), nullable=True),
    sa.Column('c_metadataxml', sa.Text(), nullable=True),
    sa.Column('c_tooltip', sa.String(length=900), nullable=True),
    sa.Column('c_comment', sa.Text(), nullable=True),
    sa.Column('c_path', sa.String(length=700), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_i2b2'))
    )
    op.create_index(op.f('ix_i2b2_id'), 'i2b2', ['id'], unique=False, postgresql_ops={})
    op.create_table('visit_dimension',
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('active_status_cd', sa.String(length=50), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('upload_id', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('patient_num', sa.Numeric(precision=38, scale=0), autoincrement=False, nullable=False),
    sa.Column('sourcesystem_cd', sa.String(length=50), nullable=True),
    sa.Column('inout_cd', sa.String(length=50), nullable=True),
    sa.Column('location_path', sa.String(length=900), nullable=True),
    sa.Column('length_of_stay', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('visit_blob', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('location_cd', sa.String(length=50), nullable=True),
    sa.Column('encounter_num', sa.Numeric(precision=38, scale=0), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('encounter_num', 'patient_num', name=op.f('pk_visit_dimension'))
    )
    op.create_index(op.f('ix_visit_dimension_encounter_num'), 'visit_dimension', ['encounter_num'], unique=False, postgresql_ops={})
    op.create_index(op.f('ix_visit_dimension_encounter_num_patient_num'), 'visit_dimension', ['encounter_num', 'patient_num'], unique=False, postgresql_ops={})
    op.create_index(op.f('ix_visit_dimension_encounter_num_patient_num_location_path_inout_cd_start_date_end_date_length_of_stay'), 'visit_dimension', ['encounter_num', 'patient_num', 'location_path', 'inout_cd', 'start_date', 'end_date', 'length_of_stay'], unique=False, postgresql_ops={u'location_path': u'varchar_pattern_ops', u'inout_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_visit_dimension_sourcesystem_cd'), 'visit_dimension', ['sourcesystem_cd'], unique=False, postgresql_ops={u'sourcesystem_cd': u'varchar_pattern_ops'})
    op.create_index(op.f('ix_visit_dimension_start_date_end_date'), 'visit_dimension', ['start_date', 'end_date'], unique=False, postgresql_ops={})
    op.create_index(op.f('ix_visit_dimension_upload_id'), 'visit_dimension', ['upload_id'], unique=False, postgresql_ops={})
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_dimension_upload_id'), table_name='visit_dimension')
    op.drop_index(op.f('ix_visit_dimension_start_date_end_date'), table_name='visit_dimension')
    op.drop_index(op.f('ix_visit_dimension_sourcesystem_cd'), table_name='visit_dimension')
    op.drop_index(op.f('ix_visit_dimension_encounter_num_patient_num_location_path_inout_cd_start_date_end_date_length_of_stay'), table_name='visit_dimension')
    op.drop_index(op.f('ix_visit_dimension_encounter_num_patient_num'), table_name='visit_dimension')
    op.drop_index(op.f('ix_visit_dimension_encounter_num'), table_name='visit_dimension')
    op.drop_table('visit_dimension')
    op.drop_index(op.f('ix_i2b2_id'), table_name='i2b2')
    op.drop_table('i2b2')
    op.drop_index(op.f('ix_patient_dimension_upload_id'), table_name='patient_dimension')
    op.drop_index(op.f('ix_patient_dimension_statecityzip_path_patient_num'), table_name='patient_dimension')
    op.drop_index(op.f('ix_patient_dimension_patient_num_vital_status_cd_birth_date_death_date_sex_cd_age_in_years_num_language_cd_race_cd_marital_status_cd_religion_cd_zip_cd_income_cd'), table_name='patient_dimension')
    op.drop_index(op.f('ix_patient_dimension_patient_num_vital_status_cd_birth_date_death_date'), table_name='patient_dimension')
    op.drop_index(op.f('ix_patient_dimension_patient_num'), table_name='patient_dimension')
    op.drop_table('patient_dimension')
    op.drop_index(op.f('ix_concept_dimension_upload_id'), table_name='concept_dimension')
    op.drop_index(op.f('ix_concept_dimension_concept_path'), table_name='concept_dimension')
    op.drop_table('concept_dimension')
    op.drop_index(op.f('ix_observation_fact_patient_num_start_date_concept_cd_encounter_num_instance_num_nval_num_tval_char_valtype_cd_modifier_cd_valueflag_cd_provider_id_quantity_num_units_cd_end_date_location_cd_confidence_num_update_date_download_date_import_date_sourcesystem_cd_upload_id'), table_name='observation_fact')
    op.drop_index(op.f('ix_observation_fact_patient_num_concept_cd_start_date_end_date_encounter_num_instance_num_provider_id_nval_num_valtype_cd'), table_name='observation_fact')
    op.drop_index(op.f('ix_observation_fact_patient_num_concept_cd_modifier_cd_start_date_encounter_num_instance_num_provider_id'), table_name='observation_fact')
    op.drop_index(op.f('ix_observation_fact_encounter_num'), table_name='observation_fact')
    op.drop_index(op.f('ix_observation_fact_concept_cd_instance_num_patient_num_encounter_num'), table_name='observation_fact')
    op.drop_index(op.f('ix_observation_fact_concept_cd'), table_name='observation_fact')
    op.drop_table('observation_fact')
    ### end Alembic commands ###
